cloud/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
]

config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

from django.contrib.sitemaps.views import sitemap


from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^$', views.index, name="index"),
    url(r'^index/', views.index, name="index"),
    url(r'^.well-known/pki-validation/$', views.ssl_verification, name="ssl-verification"),
    url(r'^company/', include('company.urls')),
    url(r'^datacenter/', include('datacenter.urls', namespace="datacenter")),
    url(r'^cloud/', include('cloud.urls', namespace="cloud")),
    url(r'^support/', include('support.urls', namespace="support")),
    url(r'^staffing/', include('staffing.urls', namespace="staffing")),
    url(r'^terms/', views.terms, name="terms"),
    
    # SEO
    url(r'^robots\.txt$', views.robot_txt),
    url(r'^sitemap\.xml$', views.sitemap),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/templatetags/app-navigation.html
{% load static %}

<nav id="navbar-fixed" class="navbar navbar-default navbar-fixed-top">
	<div class="container">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<div class="secondary-btns">
				<a href="tel:1-800-862-5144"><i class="fa fa-phone" aria-hidden="true"></i></a>
				<a href="" class="openSideNav"><i class="fa fa-bars navopen" aria-hidden="true"></i></a>
			</div>
			<a class="navbar-brand" href="{% url 'index' %}">
				<img src="{% static 'images/company/logo.png' %}">
			</a>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav navbar-right">
				<li>
					<p class="navbar-text navbar-lg-text">1.800.862.5144</p>
				</li>
				<li class="navbar-lg-text">
					<a href="#" class="openSideNav dropdown-toggle" data-toggle="offcanvas">
						<i class="fa fa-bars navopen" aria-hidden="true"></i>
					</a>
				</li>
			</ul>
		</div><!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
</nav>

<div id="mySidenav" class="sidenav">
	<a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>

	<h4>Learn more about</h4>
	<a href="{% url 'datacenter:index' %}">Modern Data Center</a>
	<a href="{% url 'cloud:index' %}">Cloud Implementation</a>
	<a href="{% url 'support:index' %}">Smart Support</a>
	<a href="{% url 'staffing:index' %}">Tech Staffing</a>
	<br>
	<a href="{% url 'company' %}">Company</a>

	<h4>Contact Us</h4>
	<a style="font-size: 1em;" href="tel:1-800-862-5144">United States: +1.800.862.5144</a>
	<a style="font-size: 1em;" href="tel:1-213-286-0733">International: +1.213.286.0733</a>
	<a style="font-size: 1em;" href="mailto:support@mibura.com">support@mibura.com</a>
	<a style="font-size: 1em;" href="mailto:sales@mibura.com">sales@mibura.com</a>
	<div class="nav-social-links link-blue" style="font-size: 3.5em;">
        <!-- Facebook -->
        <a href="https://www.facebook.com/miburainc/">
            <i class="fa fa-facebook-official" aria-hidden="true"></i>
        </a>
        <!-- Twitter -->
        <a href="#">
            <i class="fa fa-twitter-square" aria-hidden="true"></i>
        </a>
        <!-- Slack -->
        <a href="#">
            <i class="fa fa-slack openchat" aria-hidden="true"></i>
        </a>
        <!-- LinkedIn -->
        <a href="https://www.linkedin.com/company/mibura-inc-">
            <i class="fa fa-linkedin-square" aria-hidden="true"></i>
        </a>
        <!-- Skype -->
        <a href="skype:mibura1?call">
            <i class="fa fa-skype" aria-hidden="true"></i>
        </a>
    </div>  
</div>


<style type="text/css">

/* The side navigation menu */
.sidenav {
	-webkit-box-shadow: -8px 3px 10px 0px rgba(0,0,0,0.2);
	-moz-box-shadow: -8px 3px 10px 0px rgba(0,0,0,0.2);
	box-shadow: -8px 3px 10px 0px rgba(0,0,0,0.2);
    height: 100%; /* 100% Full-height */
    display: block;
    width: 0; /* 0 width - change this with JavaScript */
    position: fixed; /* Stay in place */
    z-index: 99999999; /* Stay on top */
    top: 0;
    right: 0;
    background-color: #FFF; /* White */
    overflow: hidden !important;
	white-space: nowrap !important;
    padding-top: 60px; /* Place content 60px from the top */
    transition: 0.3s ease-out all; /* 0.5 second transition effect to slide in the sidenav */
}

/* The navigation menu links */
.sidenav h4 {
	color: #1678c2;
	padding: 4px 4px 4px 25px;
}
.sidenav a, .sidenav p {
    padding: 4px 4px 4px 25px;
    text-decoration: none;
    font-size: 20px;
    display: block;
    transition: 0.3s
}

.sidenav > a, .sidenav p {
    color: #515151;
}

.nav-social-links {
	padding-left: 25px;
}

.nav-social-links > a {
	display: inline-block;
	padding-left: 0;
}

/* When you mouse over the navigation links, change their color */
.sidenav > a:hover, .offcanvas a:focus{
    color: #DDD;
}

/* Position and style the close button (top right corner) */
.sidenav .closebtn {
    position: absolute;
    top: 0;
    right: 25px;
    font-size: 36px;
    margin-left: 50px;
}

/* On smaller screens, where height is less than 450px, change the style of the sidenav (less padding and a smaller font size) */
@media screen and (max-height: 450px) {
    .sidenav {padding-top: 15px;}
    .sidenav a {font-size: 18px;}
}


/* always show hamburger */
/*@media (min-width: 768px) {
    .navbar-toggle {
        display: block;
    }
}*/

</style>

<script type="text/javascript">

	// Sidebar Nav

	/* Set the width of the side navigation to 250px */
$('.openSideNav').click(function(event) {
	event.preventDefault();
    document.getElementById("mySidenav").style.width = "250px";
})

/* Set the width of the side navigation to 0 */
function closeNav() {
    document.getElementById("mySidenav").style.width = "0";
}

$(document).on('click touchstart', function(e) {
    var container = $("#mySidenav");
    var button = $(".openSideNav");
    // if the target of the click isn't the container nor a descendant of the container
    if (!container.is(e.target) && !$(e.target).hasClass("openSideNav") && !$(e.target).hasClass("navopen") && container.has(e.target).length === 0) 
    {
        container.width("0");
    }
});

// 	// Top Navbar

// 	$('#navbar-fixed').hide();

// 	(function($) {					
// 		$(document).ready(function(){										
// 				$(window).scroll(function(){													
// 						if ($(this).scrollTop() > 200) {
// 								$('#navbar-fixed').fadeIn(500);
// 						} else {
// 								$('#navbar-fixed').fadeOut(500);
// 						}
// 				});
// 		});
// })(jQuery);

</script>

templates/templatetags/company-team-carousel.html
{% load static %}

<style type="text/css">
	#image-carousel {
		height: 600px;
		background: url("{% static 'images/company/team.jpg' %}") repeat-x;
		background-size: cover;
        width: 100%;
        animation: slide 40s linear infinite;
      }

      @keyframes slide {
        0% {
            background-position: 0 0;
        }

        100% {
            background-position: 2900px 0;
        }
      }
  </style>

<div id="image-carousel">
	<div class="slide"></div>
</div>

templates/templatetags/footer.html
{% load static %}

<!-- **** FOOTER CONTENT **** -->

<div id="footer" class="footer container-fluid gray-background text-white">
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-md-3 text-center">
                <h4>
                    Sales | Support | Customer Service 
                    <br>
                    <span style="
                        font-size: 1.5em;
                        color: #ffd220;"
                    >
                        24x7x365
                    </span>
                </h4>
            </div>
            <div class="col-sm-6 col-md-3">
                <div class="row">
                    <div class="col-xs-2" style="padding-top: 15px;">
                        <img style="max-width: 30px" src="{% static 'images/icons/svg/smartphone.svg' %}">
                    </div>
                    <div class="col-xs-10">
                        <div style="padding-top: 10px;font-size: 18px; line-height: 24px;">
                            <a class="link-blue" href="tel:1-800-862-5144"> US: +1.800.862.5144</a>  
                            <br>
                            <a class="link-blue" href="tel:1-213-286-0733">INT: +1.213.286.0733</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-md-3">
                <div class="row">
                    <div class="col-xs-2" style="padding-top: 15px;">
                        <img style="max-width: 30px" src="{% static 'images/icons/svg/chat-speech-bubbles.svg' %}">
                    </div>
                    <div class="col-xs-10">
                        <a class="openchat"><h3 style="cursor: pointer;">Live Slack</h3></a>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-md-3">
                <div class="row">
                    <div class="col-xs-2" style="padding-top: 15px;">
                        <img style="max-width: 30px" src="{% static 'images/icons/svg/close-envelope.svg' %}">
                    </div>
                    <div class="col-xs-10">
                        <a href="mailto:support@mibura.com"><h3>Email Us</h3></a>
                    </div>
                </div>
            </div>
        </div>
    
        <hr>

        <div class="row">
            <div class="col-xs-5 col-md-1">
                <h4>
                    About
                </h4>
                <a href="{% url 'index' %}">Home</a><br>
                <a href="{% url 'company' %}">Careers</a>
            </div>
            <div class="col-xs-7 col-md-2">
                <h4>
                    Products and Services
                </h4>
                <a href="{% url 'datacenter:index' %}">Modern Data Center</a><br>
                <a href="{% url 'cloud:index' %}">Cloud Implementation</a><br>
                <a href="{% url 'support:index' %}">Smart Support</a><br>
                <a href="{% url 'staffing:index' %}">Tech Staffing</a>
            </div>
            
            <div class="col-xs-12 col-md-4 text-center link-blue footer-social-links">
                <!-- Facebook -->
                <a href="https://www.facebook.com/miburainc/">
                    <i class="fa fa-facebook-official" aria-hidden="true"></i>
                </a>
                <!-- Twitter -->
                <a href="#">
                    <i class="fa fa-twitter-square" aria-hidden="true"></i>
                </a>
                <!-- Slack -->
                <a href="#">
                    <i class="fa fa-slack" aria-hidden="true"></i>
                </a>
                <!-- LinkedIn -->
                <a href="https://www.linkedin.com/company/mibura-inc-">
                    <i class="fa fa-linkedin-square" aria-hidden="true"></i>
                </a>
                <!-- Skype -->
                <a href="skype:mibura1?call">
                    <i class="fa fa-skype" aria-hidden="true"></i>
                </a>
            </div>
            <div class="col-xs-12 col-md-5">
                <div>
                    <p style="font-size: 0.9em">
                         ©2017 Mibura, Inc. All Rights reserved - Cisco, Dell EMC, Docker, Intel, Xeon Logo, Oracle, Hitachi Data System, HPE, NetApp, SuperMicro, Microsoft, Microsoft Azure, Microsoft Office 365, Amazon Web Services, Google Compute Platform, VMware, Redhat, Splunk, IBM, Fortinet, Ixia, F5,  and Nutanix are trademarks of Corporations in the U.S. and/or other countries.
                    </p>
                </div>  
            </div>
        </div>
    </div>
</div> <!--footer-->

templates/templatetags/intercom.html
<script>
	$(document).ready(function() {        
		$('.openchat').click(function() {
			Intercom('show');
		});
	});
	window.intercomSettings = {
		
		app_id: "smyxgzc7"
	};
</script>

<script>(function(){var w=window;var ic=w.Intercom;if(typeof ic==="function"){ic('reattach_activator');ic('update',intercomSettings);}else{var d=document;var i=function(){i.c(arguments)};i.q=[];i.c=function(args){i.q.push(args)};w.Intercom=i;function l(){var s=d.createElement('script');s.type='text/javascript';s.async=true;s.src='https://widget.intercom.io/widget/smyxgzc7';var x=d.getElementsByTagName('script')[0];x.parentNode.insertBefore(s,x);}if(w.attachEvent){w.attachEvent('onload',l);}else{w.addEventListener('load',l,false);}}})()</script>

templates/templatetags/navigation.html
{% load static %}

<!-- Top static Navbar -->
<nav id="navbar-static" class="navbar navbar-default navbar-static-top">
	<div class="container">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<div class="secondary-btns">

				<a href="tel:1-800-862-5144"><i class="fa fa-phone" aria-hidden="true"></i></a>
				<a href="" class="openSideNav"><i class="fa fa-bars navopen" aria-hidden="true"></i></a>
			</div>

			<a class="navbar-brand" href="{% url 'index' %}">
				<img src="{% static 'images/company/logo-white.png' %}">
			</a>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav navbar-right">
				<li>
					<p class="navbar-text navbar-lg-text">1.800.862.5144</p>
				</li>
				<li class="navbar-lg-text">
					<a href="#" class="openSideNav dropdown-toggle" data-toggle="offcanvas">
						<i class="fa fa-bars navopen" aria-hidden="true"></i>
					</a>
				</li>
			</ul>
		</div><!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
</nav>

<!-- Fixed Navbar -->

<nav id="navbar-fixed" class="navbar navbar-default navbar-fixed-top">
	<div class="container">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<div class="secondary-btns">
				<a href="tel:1-800-862-5144"><i class="fa fa-phone" aria-hidden="true"></i></a>
				<a href="" class="openSideNav"><i class="fa fa-bars navopen" aria-hidden="true"></i></a>
			</div>
			<a class="navbar-brand" href="{% url 'index' %}">
				<img src="{% static 'images/company/logo.png' %}">
			</a>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav navbar-right">
				<li>
					<p class="navbar-text navbar-lg-text">1.800.862.5144</p>
				</li>
				<li class="navbar-lg-text">
					<a href="#" class="openSideNav dropdown-toggle" data-toggle="offcanvas">
						<i class="fa fa-bars navopen" aria-hidden="true"></i>
					</a>
				</li>
			</ul>
		</div><!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
</nav>

<div id="mySidenav" class="sidenav">
	<a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>

	<h4>Learn more about</h4>
	<a href="{% url 'datacenter:index' %}">Modern Data Center</a>
	<a href="{% url 'cloud:index' %}">Cloud Implementation</a>
	<a href="{% url 'support:index' %}">Smart Support</a>
	<a href="{% url 'staffing:index' %}">Tech Staffing</a>
	<br>
	<a href="{% url 'company' %}">Company</a>

	<h4>Contact Us</h4>
	<a style="font-size: 1em;" href="tel:1-800-862-5144">United States: +1.800.862.5144</a>
	<a style="font-size: 1em;" href="tel:1-213-286-0733">International: +1.213.286.0733</a>
	<a style="font-size: 1em;" href="mailto:support@mibura.com">support@mibura.com</a>
	<a style="font-size: 1em;" href="mailto:sales@mibura.com">sales@mibura.com</a>
	<div class="nav-social-links link-blue" style="font-size: 3.5em;">
        <!-- Facebook -->
        <a href="https://www.facebook.com/miburainc/">
            <i class="fa fa-facebook-official" aria-hidden="true"></i>
        </a>
        <!-- Twitter -->
        <a href="#">
            <i class="fa fa-twitter-square" aria-hidden="true"></i>
        </a>
        <!-- Slack -->
        <a href="#">
            <i class="fa fa-slack openchat" aria-hidden="true"></i>
        </a>
        <!-- LinkedIn -->
        <a href="https://www.linkedin.com/company/mibura-inc-">
            <i class="fa fa-linkedin-square" aria-hidden="true"></i>
        </a>
        <!-- Skype -->
        <a href="skype:mibura1?call">
            <i class="fa fa-skype" aria-hidden="true"></i>
        </a>
    </div>  
</div>


<style type="text/css">

/* The side navigation menu */
.sidenav {
	-webkit-box-shadow: -8px 3px 10px 0px rgba(0,0,0,0.2);
	-moz-box-shadow: -8px 3px 10px 0px rgba(0,0,0,0.2);
	box-shadow: -8px 3px 10px 0px rgba(0,0,0,0.2);
    height: 100%; /* 100% Full-height */
    display: block;
    width: 0; /* 0 width - change this with JavaScript */
    position: fixed; /* Stay in place */
    z-index: 99999999; /* Stay on top */
    top: 0;
    right: 0;
    background-color: #FFF; /* White */
    overflow: hidden !important;
	white-space: nowrap !important;
    padding-top: 60px; /* Place content 60px from the top */
    transition: 0.3s ease-out all; /* 0.5 second transition effect to slide in the sidenav */
}

/* The navigation menu links */
.sidenav h4 {
	color: #1678c2;
	padding: 4px 4px 4px 25px;
}
.sidenav a, .sidenav p {
    padding: 4px 4px 4px 25px;
    text-decoration: none;
    font-size: 20px;
    display: block;
    transition: 0.3s
}

.sidenav > a, .sidenav p {
    color: #515151;
}

.nav-social-links {
	padding-left: 25px;
}

.nav-social-links > a {
	display: inline-block;
	padding-left: 0;
}

/* When you mouse over the navigation links, change their color */
.sidenav > a:hover, .offcanvas a:focus{
    color: #DDD;
}

/* Position and style the close button (top right corner) */
.sidenav .closebtn {
    position: absolute;
    top: 0;
    right: 25px;
    font-size: 36px;
    margin-left: 50px;
}

/* On smaller screens, where height is less than 450px, change the style of the sidenav (less padding and a smaller font size) */
@media screen and (max-height: 450px) {
    .sidenav {padding-top: 15px;}
    .sidenav a {font-size: 18px;}
}


/* always show hamburger */
/*@media (min-width: 768px) {
    .navbar-toggle {
        display: block;
    }
}*/

</style>

<script type="text/javascript">

	// Sidebar Nav

	/* Set the width of the side navigation to 250px */
$('.openSideNav').click(function(event) {
	event.preventDefault();
    document.getElementById("mySidenav").style.width = "250px";
})

/* Set the width of the side navigation to 0 */
function closeNav() {
    document.getElementById("mySidenav").style.width = "0";
}

$(document).on('click touchstart', function(e) {
    var container = $("#mySidenav");
    var button = $(".openSideNav");
    // if the target of the click isn't the container nor a descendant of the container
    if (!container.is(e.target) && !$(e.target).hasClass("openSideNav") && !$(e.target).hasClass("navopen") && container.has(e.target).length === 0) 
    {
        container.width("0");
    }
});

	// Top Navbar

	$('#navbar-fixed').hide();

	(function($) {					
		$(document).ready(function(){										
				$(window).scroll(function(){													
						if ($(this).scrollTop() > 200) {
								$('#navbar-fixed').fadeIn(500);
						} else {
								$('#navbar-fixed').fadeOut(500);
						}
				});
		});
})(jQuery);

</script>

templates/templatetags/support-navigation.html
{% load static %}

<nav id="navbar-fixed" class="navbar navbar-default navbar-fixed-top">
	<div class="container">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<div class="secondary-btns">
				<a href="tel:1-800-862-5144"><i class="fa fa-phone" aria-hidden="true"></i></a>
				<a href="" class="openSideNav"><i class="fa fa-bars navopen" aria-hidden="true"></i></a>
			</div>
			<a class="navbar-brand" href="{% url 'index' %}">
				<img src="{% static 'images/company/logo.png' %}">
			</a>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav navbar-right">
				<li>
					<p class="navbar-text navbar-lg-text">1.800.862.5144</p>
				</li>
				<li class="navbar-lg-text">
					<a href="#" class="openSideNav dropdown-toggle" data-toggle="offcanvas">
						<i class="fa fa-bars navopen" aria-hidden="true"></i>
					</a>
				</li>
			</ul>
		</div><!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
</nav>

<div id="mySidenav" class="sidenav">
	<a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>

	<h4>Learn more about</h4>
	<a href="{% url 'datacenter:index' %}">Modern Data Center</a>
	<a href="{% url 'cloud:index' %}">Cloud Implementation</a>
	<a href="{% url 'support:index' %}">Smart Support</a>
	<a href="{% url 'staffing:index' %}">Tech Staffing</a>
	<br>
	<a href="{% url 'company' %}">Company</a>

	<h4>Contact Us</h4>
	<a style="font-size: 1em;" href="tel:1-800-862-5144">United States: +1.800.862.5144</a>
	<a style="font-size: 1em;" href="tel:1-213-286-0733">International: +1.213.286.0733</a>
	<a style="font-size: 1em;" href="mailto:support@mibura.com">support@mibura.com</a>
	<a style="font-size: 1em;" href="mailto:sales@mibura.com">sales@mibura.com</a>
	<div class="nav-social-links link-blue" style="font-size: 3.5em;">
        <!-- Facebook -->
        <a href="https://www.facebook.com/miburainc/">
            <i class="fa fa-facebook-official" aria-hidden="true"></i>
        </a>
        <!-- Twitter -->
        <a href="#">
            <i class="fa fa-twitter-square" aria-hidden="true"></i>
        </a>
        <!-- Slack -->
        <a href="#">
            <i class="fa fa-slack openchat" aria-hidden="true"></i>
        </a>
        <!-- LinkedIn -->
        <a href="https://www.linkedin.com/company/mibura-inc-">
            <i class="fa fa-linkedin-square" aria-hidden="true"></i>
        </a>
        <!-- Skype -->
        <a href="skype:mibura1?call">
            <i class="fa fa-skype" aria-hidden="true"></i>
        </a>
    </div>  
</div>


<style type="text/css">

/* The side navigation menu */
.sidenav {
	-webkit-box-shadow: -8px 3px 10px 0px rgba(0,0,0,0.2);
	-moz-box-shadow: -8px 3px 10px 0px rgba(0,0,0,0.2);
	box-shadow: -8px 3px 10px 0px rgba(0,0,0,0.2);
    height: 100%; /* 100% Full-height */
    display: block;
    width: 0; /* 0 width - change this with JavaScript */
    position: fixed; /* Stay in place */
    z-index: 99999999; /* Stay on top */
    top: 0;
    right: 0;
    background-color: #FFF; /* White */
    overflow: hidden !important;
	white-space: nowrap !important;
    padding-top: 60px; /* Place content 60px from the top */
    transition: 0.3s ease-out all; /* 0.5 second transition effect to slide in the sidenav */
}

/* The navigation menu links */
.sidenav h4 {
	color: #1678c2;
	padding: 4px 4px 4px 25px;
}
.sidenav a, .sidenav p {
    padding: 4px 4px 4px 25px;
    text-decoration: none;
    font-size: 20px;
    display: block;
    transition: 0.3s
}

.sidenav > a, .sidenav p {
    color: #515151;
}

.nav-social-links {
	padding-left: 25px;
}

.nav-social-links > a {
	display: inline-block;
	padding-left: 0;
}

/* When you mouse over the navigation links, change their color */
.sidenav > a:hover, .offcanvas a:focus{
    color: #DDD;
}

/* Position and style the close button (top right corner) */
.sidenav .closebtn {
    position: absolute;
    top: 0;
    right: 25px;
    font-size: 36px;
    margin-left: 50px;
}

/* On smaller screens, where height is less than 450px, change the style of the sidenav (less padding and a smaller font size) */
@media screen and (max-height: 450px) {
    .sidenav {padding-top: 15px;}
    .sidenav a {font-size: 18px;}
}


/* always show hamburger */
/*@media (min-width: 768px) {
    .navbar-toggle {
        display: block;
    }
}*/

</style>

<script type="text/javascript">

	// Sidebar Nav

	/* Set the width of the side navigation to 250px */
$('.openSideNav').click(function(event) {
	event.preventDefault();
    document.getElementById("mySidenav").style.width = "250px";
})

/* Set the width of the side navigation to 0 */
function closeNav() {
    document.getElementById("mySidenav").style.width = "0";
}

$(document).on('click touchstart', function(e) {
    var container = $("#mySidenav");
    var button = $(".openSideNav");
    // if the target of the click isn't the container nor a descendant of the container
    if (!container.is(e.target) && !$(e.target).hasClass("openSideNav") && !$(e.target).hasClass("navopen") && container.has(e.target).length === 0) 
    {
        container.width("0");
    }
});

// 	// Top Navbar

// 	$('#navbar-fixed').hide();

// 	(function($) {					
// 		$(document).ready(function(){										
// 				$(window).scroll(function(){													
// 						if ($(this).scrollTop() > 200) {
// 								$('#navbar-fixed').fadeIn(500);
// 						} else {
// 								$('#navbar-fixed').fadeOut(500);
// 						}
// 				});
// 		});
// })(jQuery);

</script>