cloud/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
]

config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

from django.contrib.sitemaps.views import sitemap


from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^$', views.index, name="index"),
    url(r'^index/', views.index, name="index"),
    url(r'^.well-known/pki-validation/$', views.ssl_verification, name="ssl-verification"),
    url(r'^company/', include('company.urls')),
    url(r'^datacenter/', include('datacenter.urls', namespace="datacenter")),
    url(r'^cloud/', include('cloud.urls', namespace="cloud")),
    url(r'^support/', include('support.urls', namespace="support")),
    url(r'^staffing/', include('staffing.urls', namespace="staffing")),
    url(r'^terms/', views.terms, name="terms"),
    
    # SEO
    url(r'^robots\.txt$', views.robot_txt),
    url(r'^sitemap\.xml$', views.sitemap),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

support/urls.py
from django.conf.urls import url, include

from rest_framework import routers

from . import views

router = routers.DefaultRouter()

router.register(r'products', views.ProductViewSet)
router.register(r'productcomplete', views.ProductAutocompleteViewSet)
router.register(r'cloud', views.CloudViewSet)
router.register(r'categories', views.CategoriesViewSet)
router.register(r'discounts', views.DiscountViewSet)
router.register(r'plan', views.PlanViewSet)



urlpatterns = [
	url(r'^$', views.index, name="index"),
	url(r'^purchase/$', views.purchase, name="purchase"),
	
	# API
	url(r'^save-client/$', views.save_client_json, name="save_client"),
	url(r'^get-or-create-cart/$', views.get_create_cart, name="get_create_cart"),
	url(r'^get-cart/$', views.get_cart, name="get_cart"),
	url(r'^get-or-create-client/$', views.get_create_client, name="get_create_client"),
	url(r'^get-estimate-pdf/$', views.get_estimate_pdf, name="get_estimate_pdf"),
	url(r'^generate/pdf/$', views.estimate_pdf, name='generate_pdf'),
	url(r'^send-quote-email/$', views.email_estimate_pdf, name="send_quote_email"),
	url(r'^get-previous-estimate/$', views.get_previous_estimate, name="get_previous_estimate"),
	url(r'^checkout/$', views.checkout, name="checkout"),
	# Stripe and Payments
	url(r'^plaid-credentials/$', views.plaid_credentials, name="plaid_credentials"),
	url(r'^ach-credentials/$', views.stripe_ach_begin, name="ach_credentials"),
	url(r'^ach-verify/$', views.verify_ach, name="ach_verify"),
	url(r'^create-purchase-order/$', views.create_purchaseorder, name="create_purchaseorder"),
	url(r'^create-payment-object/$', views.create_payment_object, name="create_payment_object")
]



urlpatterns += [
	url(r'^api/', include(router.urls)),
]

support/views.py
from datetime import datetime, date, timedelta
from wsgiref.util import FileWrapper
import os, json, math, stripe, plaid
from copy import deepcopy

from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.core.exceptions import ObjectDoesNotExist
from django.utils import timezone, encoding
from django.template import RequestContext, Context, loader
from django.template.loader import render_to_string, get_template
from django.core.mail import EmailMessage
from django.db.models import Q
from django.utils.dateformat import DateFormat

from rest_framework import viewsets
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.renderers import JSONRenderer
from rest_framework.request import Request

from payment.models import *
from .models import *
from .serializers import *

from scripts.dotdict import dotdict
from scripts.sss_pricing import product_price, cloud_price, unknown_product_price
from freshbooks import estimates, invoices

# from weasyprint import HTML
import tempfile

stripe.api_key = settings.STRIPE_SECRET_KEY


#################
# Email
#################

def send_quote_email(name, recipient, subject, file):
	to = [recipient]
	from_email = 'cs@mibura.com'

	print(name)

	ctx = {
		'name': name,
	}

	message = get_template('email/quote.html').render(ctx)
	msg = EmailMessage(subject, message, to=to, from_email=from_email)
	msg.attach_file(file)
	msg.content_subtype = 'html'
	return msg.send()

def send_purchasesuccess_email(name, recipient, subject, length):
	to = [recipient]
	from_email = 'cs@mibura.com'

	date = datetime.now()
	account_manager = "Imran Mirza"
	vendor_engineer = ""
	infrastructure_engineer = "Imran Mirza"
	num_engineers = "22"
	sales_support = "Imran Mirza"

	brands = ['Dell']

	print(name)

	ctx = {
		'name': name,
		'date': date,
		'account_manager': account_manager,
		'vendor_engineer': vendor_engineer,
		'num_engineers': num_engineers,
		'infrastructure_engineer': infrastructure_engineer,
		'sales_support': sales_support,
		'engineer': "Imran Mirza",
		'brands': brands,
		'length': length
	}

	message = get_template('email/purchase_success.html').render(ctx)
	msg = EmailMessage(subject, message, to=to, from_email=from_email)
	msg.content_subtype = 'html'
	return msg.send()

#################
# Pages
#################

def index(request):
	"""
	View function for home page of site.
	"""
	# Render the HTML template index.html with the data in the context variable
	context = {}
	context['DEBUG'] = settings.DEBUG

	return render(
		request,
		'support/support.html',
		context
	)

def purchase(request):
	"""
	View function for home page of site.
	"""

	# Render the HTML template index.html with the data in the context variable
	context = {}
	context['DEBUG'] = settings.DEBUG
	
	return render(
		request,
		'support/app.html',
		context
	)

#################
# Api endpoints 
#################



# Stripe

@csrf_exempt
def plaid_credentials(request):
	# plaid.Client.config({'url': 'https://tartan.plaid.com'})

	if request.method == 'POST':
		data = json.loads(request.body.decode("utf-8"))
		# data = json.loads(request.body)
		data = dotdict(data) # access properties with . instead of []

		plaid_account_id = data.ach_account_id
		plaid_link_public_key = data.ach_public_key
		print("plaid_account_id", plaid_account_id)
		print("plaid_link_public_key", plaid_link_public_key)

		client = plaid.Client(settings.PLAID_CLIENT_ID,
				settings.PLAID_SECRET_KEY,
				settings.PLAID_PUBLIC_KEY,
				'sandbox')
		print("client", client.__dict__)
		exchange_token_response = client.Item.public_token.exchange(plaid_link_public_key)
		print("exchange_token_response", exchange_token_response)
		access_token = exchange_token_response['access_token']
		stripe_response = client.Processor.stripeBankAccountTokenCreate(access_token, plaid_account_id)
		bank_account_token = stripe_response['stripe_bank_account_token']

		return HttpResponse(bank_account_token, status=200)


	return HttpResponse("failed", status=400)

@csrf_exempt
def create_purchaseorder(request):
	print("create_purchaseorder")
	
	if request.method == 'POST':
		data = json.loads(request.body.decode("utf-8"))
		# data = json.loads(request.body)
		data = dotdict(data) # access properties with . instead of []
		cart = get_object_or_404(Cart, reference=data.cart_ref)
		client = get_object_or_404(Client, pk=data.client_id)
		obj = PurchaseOrder.objects.create(client=client, cart=cart, po_number=data.ponumber)
		

		return HttpResponse("True", status=200)


	return HttpResponse("failed", status=400)

@csrf_exempt
def stripe_ach_begin(request):
	print("stripe_ach_begin")

	if request.method == 'POST':
		data = json.loads(request.body.decode("utf-8"))
		# data = json.loads(request.body)
		data = dotdict(data) # access properties with . instead of []

		# Get the bank token submitted by the form
		token_id = data.stripeAchToken
		client_id = data.client_id

		# Get client object
		client = get_object_or_404(Client, pk=client_id)
		
		# Create StripeClient object and link to Client object
		stripe_client = StripeClient.create(client)

		# Link bank account to StripeClient object
		response = stripe_client.stripe_create_bank(token_id)
		
		# print response for debugging
		print("stripe_ach_begin")
		print(response)

		if response['status'] == "new":
			return HttpResponse(True, status=200)
		else:
			return HttpResponse(status=400)

	return HttpResponse("not post", status=400)

@csrf_exempt
def verify_ach(request):
	print('verify_ach')

	if request.method == 'POST':
		data = json.loads(request.body.decode("utf-8"))
		# data = json.loads(request.body)
		data = dotdict(data) # access properties with . instead of []

		# Get ACH Verify amounts
		ach_verify_amt1 = data.ach_verify_amt1
		ach_verify_amt2 = data.ach_verify_amt2

		# Debugging
		print('ach_verify_amt1', ach_verify_amt1)
		print('ach_verify_amt2', ach_verify_amt2)

		# Get client object
		client_id = data.client_id
		client = get_object_or_404(Client, pk=client_id)

		response = client.stripeclient.stripe_verify_bank_ach(ach_verify_amt1, ach_verify_amt2)
		print(response)
		if response['status'] == "verified":
			return HttpResponse({"message": "Success"}, status=200)
		else:
			return HttpResponse(response['error'], status=400)

	return HttpResponse("not post", status=400)

@csrf_exempt
def get_create_client(request):
	if request.method == 'POST':
		data = json.loads(request.body.decode("utf-8"))
		# data = json.loads(request.body)
		data = dotdict(data) # access properties with . instead of []

		obj,created = Client.objects.get_or_create(email=data.email)
		if created:
			obj.first_name = data.first_name
			obj.last_name = data.last_name
			obj.phone = data.phone
			obj.company = data.company
			obj.street = data.street
			if data.street2:
				obj.street2 = data.street2
			obj.city = data.city
			obj.state = data.state
			obj.country = data.country
			obj.zipcode = data.zipcode
			obj.save()

			return HttpResponse(obj.pk, status=201)
		else:
			obj.save()
			for field,value in obj.__dict__.items():
				if not value and field in data:
					setattr(obj, field, data[field])
			# After loop, save object and return
			obj.save()

			return HttpResponse(obj.pk, status=200)

@csrf_exempt
def save_client_json(request):
	print("save_client_json")
	if request.method == 'POST':
		data = json.loads(request.body.decode("utf-8"))
		print('Raw Data: "%s"' % data)
	return HttpResponse("OK")

@csrf_exempt
def get_cart(request):
	print("get_cart")
	if request.method == 'POST':
		data = json.loads(request.body.decode("utf-8"))
		data = dotdict(data)

		try:
			cart = Cart.objects.get(reference=data.reference)
		except ObjectDoesNotExist:
			freshbooks_estimate_id = estimates.find_estimate(data.reference)
			eid = int(freshbooks_estimate_id)
			cart = get_object_or_404(Cart, freshbooks_estimate_id=eid)

		client = get_object_or_404(Client, pk=int(cart.client.pk))
		plan_obj = Plan.objects.get(short_name=cart.plan)
		categories = ProductCategory.objects.all()

		items = []

		for client_prod in cart.products.all():

			if(client_prod.product != None):
				product = {}
				product.update(client_prod.product.__dict__)
				product.update(client_prod.__dict__)
				product['sn'] = client_prod.serial_number
				product['type'] = 'product'
				product['verified'] = True
				product['age'] = client_prod.product.release

				del(product['_state'])
				del(product['_product_cache'])

				product.update({'category':client_prod.product.category.__dict__})
				del(product['category']['_state'])

				items.append(product)

			elif(client_prod.unknown != None):
				product = {}
				product.update(client_prod.unknown.__dict__)
				product.update(client_prod.__dict__)
				product['sn'] = client_prod.serial_number
				product['type'] = 'unknown'
				product['verified'] = False
				product['age'] = client_prod.unknown.device_age
				product['price_silver'] = 1.0
				product['price_gold'] = 1.0
				product['price_black'] = 1.0

				del(product['_state'])
				del(product['_unknown_cache'])

				product.update({'category': {
									'category_code': 'none',
									'name': 'None',
									'price_multiplier': 1.0,
									'yearly_tax': 0.1,
								}})

				print("UNKNOWN")
				print(product)

				items.append(product)

			elif(client_prod.cloud != None):
				cloud_item = client_prod.cloud.__dict__
				cloud_item['category'] = categories.get(category_code='none').__dict__
				del(cloud_item['_state'])
				del(cloud_item['category']['_state'])
				cloud_item['price_silver'] = 1.0
				cloud_item['price_gold'] = 0.0
				cloud_item['price_black'] = 0.0
				cloud_item['model'] = cloud_item['name']
				cloud_item['type'] = 'cloud'
				cloud_item['quantity'] = client_prod.quantity

				items.append(cloud_item)

		serializer_context = {

templates/support/purchase.html
{% extends 'base-support.html' %}
{% load static %}


{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/support-style.css' %}">

<style type="text/css">
	body {
		background-color: #f6f6f6; 
	}
</style>
{% endblock %}

{% block title %}
Support -
{% endblock %}

{% block content %}
<div id="app"></div>

{% endblock %}

{% block javascript %}

<script src="{% static 'supportbundle/build.js' %}"></script>

{% endblock %}

templates/support/support.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Support
{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/support-style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/label.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/card.min.css' %}">



<style type="text/css">
	
#support-header {
	padding-top: 100px;
	margin-top: -50px;
	/*background-image: linear-gradient( rgba(0, 0, 0, 0.2), rgba(0, 0, 0, 0.5) ), url({% static 'images/backgrounds/clouds.jpg' %});*/
	/*background-position: center;*/
	/*background-size: cover;*/
	/*background-repeat: no-repeat;*/
}

tr td:not(:first-child) {
	text-align: center;
}

.vertical-border {
	border-color: #cccccc;
	border-left: 1px solid;
	border-right: 1px solid;
	/*height: 250px;*/
	line-height: 250px;
	text-align: center;
}

@media (max-width: 767px) {
	#support-compare-table {
		display: none;
	}
	.vertical-border {
		margin: 0;
		border-left: 0 solid;
		border-right: 0 solid;
		height: 150px;
		padding: 5px;
		line-height: 150px;
		text-align: center;
	}
	table, tbody, thead, td, tr {
		font-size: 11px!important;
	}
}

</style>

{% endblock %}

{% block content %}

<div id="support-header" class="container-fluid gray-background pad-top-bottom text-white">
	<div class="row">
		<div class="col-xs-12 text-center">
			<h1>
				Discover Smart Support
			</h1>
			<h3>
				OEM hardware and cloud partnerships, alignment with global distributors, and our first contact triage is a best of breed support platform.
			</h3>
			<br>
			<button type="button" class="btn btn-success" data-toggle="modal" data-target=".bs-example-modal-sm">Try Pure Gold for Cloud Support 14 days FREE</button>
			<!-- <a class="btn btn-success" href="{% url 'support:purchase' %}">Try Pure Gold for Cloud Support 14 days FREE</a> -->
		</div>
	</div>
</div>

<div class="container-fluid pad-top-bottom">
<div class="container">
	<div class="row text-center">
		<div class="col-xs-12">
			<h2>
				Our Support Plans are Per Device, Per Cloud Instance or Both!
			</h2>
		</div>
		<div class="col-xs-12 col-md-5">
			<img src="{% static 'images/icons/data-network.svg' %}" class="ui image" style="margin: auto;" width="40px">
			<h4>
				On Premise Data Center
			</h4>
			<p>
				(3rd Party Hardware &amp; Software Contract)
			</p>
			<div id="carousel-onpremise-support" class="carousel slide" data-ride="carousel">

				<!-- Wrapper for slides -->
				<div class="carousel-inner" role="listbox">
					<div class="item active">
						<img src="{% static 'images/support/Cisco_logo.svg.png' %}" class="img-responsive">
					</div>
					<div class="item">
						<img src="{% static 'images/support/dellemc.png' %}" class="img-responsive">
					</div>
					<div class="item">
						<img src="{% static 'images/support/docker.svg' %}" class="img-responsive">
					</div>
					<div class="item">
						<img src="{% static 'images/support/F5_Networks_logo.svg.png' %}" class="img-responsive">
					</div>
					<div class="item">
						<img src="{% static 'images/support/hpenterprise.png' %}" class="img-responsive">
					</div>
					<div class="item">
						<img src="{% static 'images/support/ixia.png' %}" class="img-responsive">
					</div>
					<div class="item">
						<img src="{% static 'images/support/linuxopensource.png' %}" class="img-responsive">
					</div>
					<div class="item">
						<img src="{% static 'images/support/microsoftserver.png' %}" class="img-responsive">
					</div>
					<div class="item">
						<img src="{% static 'images/support/microsoftwindows.png' %}" class="img-responsive">
					</div>
					<div class="item">
						<img src="{% static 'images/support/netapp.png' %}" class="img-responsive">
					</div>
					<div class="item">
						<img src="{% static 'images/support/oracle.png' %}" class="img-responsive">
					</div>
					<div class="item">
						<img src="{% static 'images/support/supermicro-logo.png' %}" class="img-responsive">
					</div>
					<div class="item">
						<img src="{% static 'images/support/vmware.png' %}" class="img-responsive">
					</div>
				</div>

				<!-- Controls -->
				<a class="left carousel-control" href="#carousel-onpremise-support" role="button" data-slide="prev">
					<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
					<span class="sr-only">Previous</span>
				</a>
				<a class="right carousel-control" href="#carousel-onpremise-support" role="button" data-slide="next">
					<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
					<span class="sr-only">Next</span>
				</a>
			</div>
		</div>
		<div class="col-xs-12 col-md-2">
			<div class="vertical-border">
				Or
			</div>
		</div>
		<div class="col-xs-12 col-md-5">
			<img src="{% static 'images/icons/cloud-network.svg' %}" class="ui image" style="margin:auto;" width="40px">
			<h4>
				Cloud Platform
			</h4>
			<p>
				(Premium Cloud Support)
			</p>
			<div id="carousel-cloud-support" class="carousel slide" data-ride="carousel">

				<!-- Wrapper for slides -->
				<div class="carousel-inner" role="listbox">
					<div class="item active">
						<img src="{% static 'images/support/MSAzure.png' %}">
					</div>
					<div class="item">
						<img src="{% static 'images/support/amazon-web-services-logo.svg' %}">
					</div>
					<div class="item">
						<img src="{% static 'images/support/office-365.png' %}">
					</div>
					<div class="item">
						<img src="{% static 'images/support/gcp.svg' %}">
					</div>
				</div>

				<!-- Controls -->
				<a class="left carousel-control" href="#carousel-cloud-support" role="button" data-slide="prev">
					<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
					<span class="sr-only">Previous</span>
				</a>
				<a class="right carousel-control" href="#carousel-cloud-support" role="button" data-slide="next">
					<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
					<span class="sr-only">Next</span>
				</a>
			</div>
		</div>
	</div>
</div>
</div>

<div class="container-fluid pad-top-bottom ltgray-background">
<div class="container" id="plan-comparison">
	<div class="row">
		<div class="col-xs-12 text-center pad-bottom">
			<h2>
				Ask Us About Carbon Black
			</h2>
			<p>
				We can create a support plan tailored for your environment with unparalleled white glove service!
			</p>
		</div>

		<!-- PRO SILVER -->

		<style type="text/css">
			.panel {
				background-color: white;
				border: 1px solid #ddd;
				-webkit-box-shadow: 0 1px 1px rgba(0,0,0,.05);
		    	box-shadow: 0 1px 1px rgba(0,0,0,.05);
			}
			.panel-heading {
				padding: 10px 15px;
			}
			.panel-body {
				padding: 15px;
			}
			.support-pricing-panel-header {
				height: 60px;
			}
		</style>

		<div class="col-xs-12 col-md-4">
			<div class="plan-panel panel panel-default">
				<div class="panel-heading">
					<div class="folded">
						<h2 style="background-color: #E8E8E8;">Pro Silver</h2>
					</div>
				</div>
				<div class="panel-body" style="padding-top: 50px;">
					<p class="support-pricing-panel-header">
						<strong>Lowest Cost On-Premise 3rd Party Hardware Support For Production Environments</strong>
					</p>
					<hr>
					<h2 style="font-size: 1em; padding-top: 2%">(4HR Response)</h2>
      				<hr>
      				<p>
      					<strong>Starting at $49/yr per asset</strong>
      				</p>
      				<hr>
      				<button class="btn btn-silver" id="select-silver" data-toggle="modal" data-target=".bs-example-modal-sm">Buy Pro Silver</button>
      				<hr>
					<ul class="list-unstyled list-altcolor">
						<li>Data Center Hardware 24x7 Certified OEM Parts NBD (same day where available)</li>
						<li>Dedicated Technical Manager</li>
						<li>Keep Your Drives</li>
						<li>OEM Authorized Firmware &amp; Software Updates</li>
						<li>Onsite Support After Diagnosis</li>
						<li>Backup &amp; Disaster Recovery Support</li>
						<li>Virtualization Support</li>
						<li>Slack, Skype, Twitter Support 24x7</li>
					</ul>
				</div>
			</div>
		</div>

		<!-- PURE GOLD -->

		<div class="col-xs-12 col-md-4">
			<div class="plan-panel panel panel-default">
				<div class="panel-heading">
					<div class="folded">
						<h2 style="background-color: #f4c730; color: white;">Pure Gold</h2>
					</div>
				</div>
				<div class="panel-body" style="padding-top: 50px;">
					<p class="support-pricing-panel-header">
						<strong>Premium Cloud and On-Premise Support. Ideal for Hybrid Environments or Basic Professional Services</strong>
					</p>
					<hr>
					<h2 style="font-size: 1em; padding-top: 2%">(15MIN Response)</h2>
      				<hr>
      				<p>
      					<strong>Starting at $99/yr per asset</strong>
      				</p>
      				<hr>
      				<button class="btn btn-gold" id="select-silver" data-toggle="modal" data-target=".bs-example-modal-sm">Buy Pure Gold</button>
      				<hr>
					<ul class="list-unstyled list-altcolor">
						<li>Includes Pro Silver</li>
						<li>Cloud Environment 24x7 Support for Break/Fix and Critical Issues</li>
						<li>On-Premise or Cloud Deployment Assistance</li>
						<li>Data &amp; Workload Migration Assistance</li>
						<li>Proactive Maintenance &amp; Reporting</li>
						<li>Database Support</li>
						<li>Dedicated Engineering &amp; Support Team</li>
						<li>Root Cause Analysis</li>
					</ul>
				</div>
			</div>
		</div>

		<!-- CARBON BLACK -->

		<div class="col-xs-12 col-md-4">
			<div class="plan-panel panel panel-default">
				<div class="panel-heading">
					<div class="folded">
						<h2 style="background-color: #000000; color: white;">Carbon Black</h2>
					</div>
				</div>
				<div class="panel-body" style="padding-top: 50px;">
					<p class="support-pricing-panel-header">
						<strong>Custom Support with Dedicated Triage Team. Ideal for Large Environments</strong>
					</p>
					<hr>
					<h2 style="font-size: 1em; padding-top: 2%">(15MIN Response)</h2>
      				<hr>
      				<p>
      					<strong>Starting at $499/yr per asset</strong>
      				</p>
      				<hr>
      				<button class="btn btn-black" id="select-silver" data-toggle="modal" data-target=".bs-example-modal-sm">Buy Carbon Black</button>
      				<hr>
					<ul class="list-unstyled list-altcolor">
						<li>Includes Pure Gold</li>
						<li>Support's Multiple Data Centers Globally</li>
						<li>Dedicated Security &amp; Compliance Team</li>
						<li>Architecture, Consulting, and Advisory Services</li>
						<li>Dedicated Server/Client Patch Management Team (up to 10,000 devices)</li>
					</ul>
				</div>
			</div>
		</div>
		
	</div>
</div>
</div>

<div id="support-compare-table" class="container pad-top-bottom">
	<div class="row text-center pad-bottom">
		<div class="col-xs-12">
			<h2>See How We Stack Up Against Other Companies</h2>
		</div>
		<div class="col-xs-12 col-md-4">
			<span style="font-size: 4em;">
				<i class="fa fa-cloud" aria-hidden="true"></i>
			</span>
			<br>
			<p>Available for Cloud Services</p>
		</div>
		<div class="col-xs-12 col-md-4">
			<span style="font-size: 4em;">
				<i class="fa fa-server" aria-hidden="true"></i>
			</span>
			<br>
			<p>Available for on Premise Services</p>
		</div>
		<div class="col-xs-12 col-md-4">
			<span style="font-size: 4em;">
				<i class="fa fa-cloud" aria-hidden="true"></i><i class="fa fa-server" aria-hidden="true"></i>
			</span>
			<br>
			<p>Available for on Premise &amp; Cloud Services</p>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12">
			{% include 'templatetags/support_compare_table.html' %}
		</div>
	</div>
</div>

<!-- Small modal -->


<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content" style="padding: 50px;">
    	<h2>Upcoming feature</h2>
      <h4>Smart Support will be available for instant purchase beginning Late August - we appreciate your patience while we bring you the best in breed support platform</h4>
    </div>
  </div>
</div>

{% endblock %}